"""
WebShop-specific code execution function for GuardAgent
"""

import sys
import traceback
from io import StringIO

def run_code_webshop(cell):
    """
    Execute guardrail code for WebShop environment.
    
    This function is called by GuardAgent to execute the generated guardrail code.
    It follows the same pattern as run_code_seeact but adapted for WebShop rules.
    
    Args:
        cell: Python code string generated by GuardAgent
        
    Returns:
        Formatted result string with action_denied, inaccessible_actions, and guardrailed_answer
    """
    try:
        global_var = {
            "action_denied": None,
            "inaccessible_actions": None,
            "guardrailed_answer": None
        }
        
        # Capture print output
        old_stdout = sys.stdout
        redirected_output = sys.stdout = StringIO()
        
        # Execute code with header
        exec(CodeHeader + cell, global_var)
        
        # Restore stdout
        sys.stdout = old_stdout
        output = redirected_output.getvalue()
        
        # Check if code executed correctly
        if not ('ACTION DENIED' in output or "ACTION GRANTED" in output):
            return "Missing variables. Code must set action_denied and guardrailed_answer."
        
        # Parse result
        if "ACTION DENIED" in output:
            action_denied = True
            guardrailed_answer = None
            inaccessible_actions = {}
            
            # Try to extract inaccessible_actions from global_var
            if global_var.get('inaccessible_actions'):
                inaccessible_actions = global_var['inaccessible_actions']
            else:
                # Fallback: try to extract from output
                inaccessible_actions = {}
        else:
            action_denied = False
            guardrailed_answer = global_var.get('guardrailed_answer', '')
            inaccessible_actions = {}
        
        # Format result
        return "GuardAgent results:\naction_denied: {}\ninaccessible_actions: {}\nguardrailed_answer: {}\n(End of results)".format(
            int(action_denied),
            inaccessible_actions,
            guardrailed_answer if guardrailed_answer else ""
        )
        
    except Exception as e:
        error_info = traceback.format_exc()
        code = CodeHeader + cell
        
        # Parse error information
        error_type = ""
        error_message = ""
        error_line = ""
        
        if "SyntaxError" in str(repr(e)):
            error_line = str(repr(e))
            error_type = error_line.split('(')[0]
            error_message = error_line.split(',')[0].split('(')[1]
            error_line = error_line.split('"')[1] if '"' in error_line else ""
        elif "KeyError" in str(repr(e)):
            code_lines = code.split('\n')
            key = str(repr(e)).split("'")[1]
            error_type = str(repr(e)).split('(')[0]
            for i in range(len(code_lines)):
                if key in code_lines[i]:
                    error_line = code_lines[i]
            error_message = str(repr(e))
        elif "TypeError" in str(repr(e)):
            error_type = str(repr(e)).split('(')[0]
            error_message = str(e)
            function_mapping_dict = {
                "check_access": "CheckAccess",
                "check_action": "CheckAction",
                "check_rule": "CheckRule"
            }
            error_key = ""
            for key in function_mapping_dict.keys():
                if key in error_message:
                    error_message = error_message.replace(key, function_mapping_dict[key])
                    error_key = function_mapping_dict[key]
            code_lines = code.split('\n')
            for i in range(len(code_lines)):
                if error_key in code_lines[i]:
                    error_line = code_lines[i]
        else:
            error_type = ""
            error_message = str(repr(e)).split("('")[-1].split("')")[0] if "('" in str(repr(e)) else str(e)
            error_line = ""
        
        # Format error message
        if error_type != "" and error_line != "":
            error_info = f'{error_type}: {error_message}. The error messages occur in the code line "{error_line}".'
        else:
            error_info = f'Error: {error_message}.'
        error_info += '\nPlease make modifications accordingly and make sure the rest code works well with the modification.'
        
        return error_info

